
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    
    - name: dim_event_types
      description: "Dimension for the types of natural events"
      columns:
          - name: event_name
            description: "The name of the event that orrured"
            tests:
              - unique
              - not_null
    
    - name: dim_sources
      description: "Dimension for the source of where the natural event was from"
      columns:
          - name: source_name
            description: "The name of the source that reported the natural event"
            tests:
              - unique
              - not_null
